apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: Cdk8sAppProxy
metadata:
  name: cdk8s-sample-app
  namespace: default
spec:
  gitRepository:
    url: "https://github.com/PatrickLaabs/cluster-api-addon-provider-cdk8s/examples/cdk8s-sample-deployment"
    reference: "main"
    path: "."
  clusterSelector: {}
    # matchLabels:
      # environment: development
